// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package orco.domain;

import org.springframework.beans.factory.annotation.Configurable;

privileged aspect OrdenCompra_Roo_Configurable {
    
    declare @type: OrdenCompra: @Configurable;
    
}
