// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package orco.domain;

import javax.persistence.Entity;

privileged aspect Presupuesto_Roo_Entity {
    
    declare @type: Presupuesto: @Entity;
    
}
