// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package orco.web;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.convert.support.GenericConversionService;

privileged aspect RemitoController_Roo_Controller {
    
    @Autowired
    private GenericConversionService RemitoController.conversionService;
    

    
}
